T17
Ashish02112001/Training pull request #22
Opened 2023-09-05 06:42 UTC by Ashish02112001

2023-09-06 05:00 UTC, asfar-nazar requested changes

2023-09-06 05:00 UTC, asfar-nazar commented on Program.cs
> +            for (int k = 0; k < tCount; k++) result[k + i * tCount] = start + remWords[k];
For clarity, better use result as a list<string> instead of string array

2023-09-06 05:00 UTC, asfar-nazar commented on Program.cs
> +         foreach (string str in Permute1 (word)) { Console.WriteLine ($"{count,4}. {str}"); count++; }
```suggestion
         foreach (string str in Permute1 (word)) { Console.WriteLine ($"{count, 4}. {str}"); count++; }
```

2023-09-06 05:00 UTC, asfar-nazar commented on Program.cs
> +         string word = "RED";
Get word as input from the user

2023-09-06 10:33 UTC, Ashish02112001 commented on Training.csproj
> -    <Nullable>enable</Nullable>
I have got null error at some line but don't know where. So i have removed it na.

2023-09-06 10:35 UTC, Ashish02112001 commented on Program.cs
> +         foreach (string str in Permute1 (word)) { Console.WriteLine ($"{count,4}. {str}"); count++; }
I don't get it na
Can you brief it?

2023-09-08 06:48 UTC, asfar-nazar requested changes

2023-09-08 06:48 UTC, asfar-nazar commented on Training.csproj
> -    <Nullable>enable</Nullable>
Undo this and use the null coalescing operator when assigning 'word' variable

2023-10-09 09:47 UTC, closed without merging