T18.1
Ashish02112001/Training pull request #24
Opened 2023-09-05 06:43 UTC by Ashish02112001

2023-09-06 06:11 UTC, asfar-nazar requested changes

2023-09-06 10:57 UTC, Ashish02112001 commented on Program.cs
> +// For example, Armstrong.exe 12 should print as 371. Maximum input can be restricted to 25.
Above 25 it takes more time to calculate na

2023-09-06 11:05 UTC, Ashish02112001 commented on Program.cs
> +         if (int.TryParse (args[0], out var num) && num <= 25) {
In the question they have asked to use command line arguments na. So i have used like this

2023-09-08 06:39 UTC, asfar-nazar requested changes

2023-09-08 06:39 UTC, asfar-nazar commented on Program.cs
> +// For example, Armstrong.exe 12 should print as 371. Maximum input can be restricted to 25.
Optimization 1: 
Each time the program is run, the list of Armstrong numbers are calculated from scratch ie to output 10th number, all 9 numbers are calculated. Try and cache the previously calculated Armstrong numbers, maybe in a text file in the program folder. 
Another optimization could be cache the powers of all 9 digits (raised to n - digits) instead of using Math.Pow

2023-09-13 06:22 UTC, asfar-nazar commented
Two changes, 

- Fix the program crash on initial run, when the cache file is not present in the program folder.

- Update nums list instead of writing each new Armstrong number to the cache file. Write the nums list to the file before program exits.

2023-09-15 13:14 UTC, asfar-nazar requested changes

2023-09-15 13:14 UTC, asfar-nazar commented on Program.cs
> +         List<int> newNums = new ();
Why use a new List when you can add the new Armstrong numbers to 'nums' ?

2023-09-21 12:00 UTC, asfar-nazar approved these changes

2023-10-09 09:47 UTC, closed without merging