T19: Factorial of a Number
Ashish02112001/Training pull request #25
Opened 2023-09-05 08:30 UTC by Ashish02112001

2023-09-06 06:28 UTC, asfar-nazar requested changes

2023-09-06 06:28 UTC, asfar-nazar commented on Program.cs
> +            if (int.TryParse (Console.ReadLine (), out var num) && num > 0 && num <= 20) {
Try and avoid the limit at 20!. Hint: search for System.Numeric

2023-09-07 08:31 UTC, Ashish02112001 commented on Program.cs
> +            if (int.TryParse (Console.ReadLine (), out var num) && num > 0 && num <= 20) {
Are you telling to use the byte na?

2023-09-08 13:19 UTC, asfar-nazar requested changes

2023-09-08 13:19 UTC, asfar-nazar commented on Program.cs
> +            } else Console.Write ("Enter a valid number below 20: ");
Is this else block necessary?

2023-09-12 06:43 UTC, asfar-nazar requested changes

2023-09-12 06:43 UTC, asfar-nazar commented on Program.cs
> +      static BigInteger Factorial (int num) => (num > 1) ? num * Factorial (num - 1) : 1;
Will this work if input is 10000? Please check.

2023-09-12 08:44 UTC, Ashish02112001 commented on Program.cs
> +      static BigInteger Factorial (int num) => (num > 1) ? num * Factorial (num - 1) : 1;
Not Working na It's Crashing.

2023-09-12 09:45 UTC, asfar-nazar approved these changes

2023-10-09 09:47 UTC, closed without merging