T20
Ashish02112001/Training pull request #26
Opened 2023-09-06 10:53 UTC by Ashish02112001

2023-09-08 06:58 UTC, asfar-nazar requested changes

2023-09-08 06:58 UTC, asfar-nazar commented on Program.cs
> +// For example, 355.56 is the input number, output = integral part: 3 5 5; factorial part: 5 6.
```suggestion
// For example, 355.56 is the input number, output = integral part: 3 5 5; fractional part: 5 6.

```

2023-09-08 06:58 UTC, asfar-nazar commented on Program.cs
> +         while (num > 0) {
You could just convert the number to a string and print individual characters

2023-09-08 06:58 UTC, asfar-nazar commented on Program.cs
> +               int fractPartx = (int) ((decimal)Math.Pow (10, fractLen) * fractPart);
With the number converted to a string, you could just use substring to get the relevant part, instead of doing this computation

2023-09-08 13:21 UTC, asfar-nazar requested changes

2023-09-08 13:21 UTC, asfar-nazar commented on Program.cs
> +               string intPart = numStr.Contains ('.') ? numStr.Substring (0, numStr.IndexOf ('.')) : numStr;
You are checking if numStr contains '.' twice when you don't need to check it at all. Hint: string 'split'

2023-09-12 06:41 UTC, asfar-nazar requested changes
What will the output be if user enters -29 as input. Should the output be - 2 9 or just 2 9 ?

2023-09-12 06:41 UTC, asfar-nazar commented on Program.cs
> +               }break;
```suggestion
               } break;

```

2023-09-12 08:54 UTC, Ashish02112001 commented
> What will the output be if user enters -29 as input. Should the output be - 2 9 or just 2 9 ?

Integral part includes the sign also na so i included.

2023-09-13 06:03 UTC, asfar-nazar approved these changes

2023-10-09 09:46 UTC, closed without merging