T23: Voting Contest
Ashish02112001/Training pull request #29
Opened 2023-09-26 06:12 UTC by Ashish02112001

2023-09-26 13:21 UTC, asfar-nazar commented on Program.cs
> +            if (S.All (char.IsAsciiLetter) && S.Length > 0) {
Why check IsAsciiLetter ?

2023-09-28 03:51 UTC, Ashish02112001 commented on Program.cs
> +            if (S.All (char.IsAsciiLetter) && S.Length > 0) {
Voting they have given for alphabets na. i Have changed to simply IsLetters now.

2023-10-05 04:39 UTC, asfar-nazar commented on Program.cs
> +            if (S.All (char.IsAsciiLetter) && S.Length > 0) {
Sorry, IsAsciiLetter is the one to be used here.

2023-10-08 12:39 UTC, asfar-nazar requested changes
Write tests to validate 'VotesCounter'

2023-10-30 09:17 UTC, asfar-nazar approved these changes

2023-10-30 09:17 UTC, closed without merging