T25: Sort and swap special character
Ashish02112001/Training pull request #31
Opened 2023-10-04 05:33 UTC by Ashish02112001

2023-10-04 08:58 UTC, ravin-imm requested changes

2023-10-04 08:58 UTC, ravin-imm commented on Program.cs
> +         Console.WriteLine ($"{string.Join (",", sp1)} {string.Join (",", sp.ToArray ())}");
I think one of the main requirements of this assignment is not met as shown below:
<img width="467" alt="image" src="https://github.com/Ashish02112001/Training/assets/75829870/677b01e6-07a0-4c4d-8538-498eb0dd3465">
Can you implement a method using any of the above keywords?

2023-10-05 04:16 UTC, ravin-imm requested changes

2023-10-05 04:16 UTC, ravin-imm commented on Program.cs
> +         return ($"{string.Join (",", filterArr)},{string.Join (",", spChr.ToArray ())}");
I am not able to compile. Please make sure that there won't be any compilation errors before your commits.

2023-10-05 09:43 UTC, ravin-imm requested changes

2023-10-05 09:43 UTC, ravin-imm commented on Program.cs
> +         Console.WriteLine ("Enter the sort order(ascending(a) or Descending(d)): ");
The message should be consistent. This can be like below:
_Enter the sort order, (a)scending or (d)escending_:

2023-10-05 09:43 UTC, ravin-imm commented on Program.cs
> +         Console.WriteLine ($"Sorted and swapped special characrter: [{SortAndSwapSplChr (A, S, O)}]");
Correct the typo in the above message.

2023-10-05 09:43 UTC, ravin-imm commented on Program.cs
> +         foreach (char c in A) if (c == S) spChr += c; else filterA += c;
The optional parameters are never used.

2023-10-05 09:43 UTC, ravin-imm commented on Program.cs
> +         return ($"{string.Join (",", filterArr)},{string.Join (",", spChr.ToArray ())}");
You are first adding all the characters to a string and then converting the string to a char array and finally using string.Join (..) to print it. Can this be simplified?

2023-10-06 09:31 UTC, ravin-imm requested changes
As per the requirement, the input characters should be alphabets; but at present numeric characters are also accepted. Modify the implementation to meet the requirement:
<img width="476" alt="image" src="https://github.com/Ashish02112001/Training/assets/75829870/a3869641-0938-4ce2-8fbf-6848c6a34c63">

2023-10-09 04:43 UTC, ravin-imm requested changes

2023-10-09 04:43 UTC, ravin-imm commented on Program.cs
> +         char[] special = A.Where (c => c == S).ToArray ();
Can these 2 operations be carried out once?

2023-10-11 04:50 UTC, ravin-imm requested changes

2023-10-11 04:50 UTC, ravin-imm commented on Program.cs
> +      static string SortAndSwapSplChr (char[] A, char S, char O = 'a') {
Generally as a convention, the function parameters should be in lowercase.

2023-10-11 04:50 UTC, ravin-imm commented on Program.cs
> +         List<char> special = new List<char> ();
The declaration can be simplified. Try to make use of Visual Studio's suggestions:
![image](https://github.com/Ashish02112001/Training/assets/75829870/7a82e8fb-a3a4-4306-86ee-f515d1149edf)

2023-10-11 05:09 UTC, Ashish02112001 commented on Program.cs
> +      static string SortAndSwapSplChr (char[] A, char S, char O = 'a') {
I have taken it as given in question, sir

2023-10-11 08:58 UTC, ravin-imm approved these changes
See my last minor cleanup.

2023-10-11 08:58 UTC, ravin-imm commented on Program.cs
> +         List<char> special = new ();
Can be:
`List<char> filtered = new (), special = new ();`

2023-10-11 08:59 UTC, closed without merging