T26: MyList<T>
Ashish02112001/Training pull request #32
Opened 2023-10-12 12:25 UTC by Ashish02112001

2023-10-13 05:02 UTC, ravin-imm requested changes

2023-10-17 09:53 UTC, ravin-imm requested changes

2023-10-17 09:53 UTC, ravin-imm commented on Program.cs
> +         }
Single line after an _if_ statement need not have braces.

2023-10-17 09:53 UTC, ravin-imm commented on Program.cs
> +         } else return false;
No need of have _else_ here since this line will be executed if the condition is not valid.

2023-10-17 09:53 UTC, ravin-imm commented on Program.cs
> +   #endregion
_#endregion_ should be placed at appropriate level.

2023-10-17 09:53 UTC, ravin-imm commented on Program.cs
> +         }
This line of code that resizes the array is repeated at multiple places. Move this to a method.

2023-10-17 09:53 UTC, ravin-imm commented on Program.cs
> +         else throw new IndexOutOfRangeException();
_else_ not required here.

2023-10-18 10:13 UTC, ravin-imm requested changes

2023-10-18 10:13 UTC, ravin-imm commented on Program.cs
> +         if (index > mSize) throw new IndexOutOfRangeException ();
First the exception has to be thrown.

2023-10-27 04:19 UTC, ravin-imm commented
I don't see any tests in your last commit. Please add tests.

2023-10-31 07:29 UTC, ravin-imm requested changes

2023-10-31 07:29 UTC, ravin-imm commented on Training/Program.cs
> +         ExpandArraySize ();
I think the better design is to first check if the array can accommodate the number to be added. If not, expand the array and then add the element. This way we will be expanding the array only if we are adding once it is full. In the above implementation, we add an element and try to expand the array if it gets full.

2023-10-31 07:29 UTC, ravin-imm commented on TestProject1/UnitTest1.cs
> +         Assert.AreEqual (8, myNums.Capacity);
This is not a valid test. Though the array has only 4 elements, the capacity has been doubled.

2023-11-01 03:45 UTC, ravin-imm requested changes

2023-11-01 03:45 UTC, ravin-imm commented on Training/Program.cs
> +         if (mSize >= Capacity) ExpandArraySize ();
There is a double check here for the array size. This check is done in _ExpandArraySize_ () method also.

2023-11-01 03:45 UTC, ravin-imm commented on TestProject1/UnitTest1.cs
> +         nums[0] = 0; myNums[0] = 0;
Why is the special treatment for the first element here?

2023-11-01 06:43 UTC, Ashish02112001 commented on TestProject1/UnitTest1.cs
> +         nums[0] = 0; myNums[0] = 0;
Just for testing the set by changing the value sir.

2023-11-01 09:58 UTC, closed without merging