A7: Double.Parse
Ashish02112001/Training pull request #38
Opened 2023-11-27 08:38 UTC by Ashish02112001

2023-12-03 13:25 UTC, meenashriTMM commented on Training/Program.cs
> +         s = s.Trim ().ToLower () ?? "";
If s is null, exception would be thrown

2023-12-03 13:31 UTC, meenashriTMM commented on Training/Program.cs
> +                     plVal = s.IndexOf ('.');
You could avoid s.Contains('.'). 
s.IndexOf('.') will return -1 if '.' is not found in the string.
Also, line 47 is also not needed. You are checking twice if '.' is presernt.

You could do as below
 var idx = s.IndexOf ('.');
plVal = idx == -1 ? s.Length : idx;

2023-12-03 13:40 UTC, meenashriTMM commented on Training/Program.cs
> +                  if (s.Contains ('e')) {
s.Contains('e') is not necessary. s.Indexof() will return -1 if not found

2023-12-03 13:41 UTC, meenashriTMM commented on Training/Program.cs
> +                     int eInd = s.IndexOf ("e");
Avoid during same operation multiple times. You are already doing this in line 42.

2023-12-03 13:43 UTC, meenashriTMM commented on Training/Program.cs
> +         string exp = "0";
Any reason why exp should be 0 but not null?

2023-12-03 13:48 UTC, meenashriTMM commented on Training/Program.cs
> +         return Math.Round (dParsedNum * sign * (Math.Pow (10, exp)),Math.Abs(exp)+fracPart);
Incorrect code formatting in this line.
Please make sure your code is formatted before commiting it

2023-12-03 13:50 UTC, meenashriTMM commented on Test/UnitTest1.cs
> +      public void TestDoubleDotParseIsTrue () {
Please change both the method names. 'Dot' in the naming is unnecessary

2023-12-03 13:50 UTC, meenashriTMM commented on Test/UnitTest1.cs
> +      public void TestDoubleDotParseIsFalse () {
Leave a line between methods

2023-12-13 10:09 UTC, meenashriTMM requested changes

2023-12-13 10:09 UTC, meenashriTMM commented on Training/Program.cs
> +         s = s.Trim ().ToLower ();
You should do the null check in line 36 first. If its null, s.Trim () would throw exception here itself.

2023-12-13 10:09 UTC, meenashriTMM commented on Training/Program.cs
> +         string exp = "0";
Any reason yet?

2023-12-13 12:10 UTC, Ashish02112001 commented on Training/Program.cs
> +         string exp = "0";
If exponent is not given it will take "0" and parse it so that it will be number * 10^0 ka.

2023-12-14 05:34 UTC, meenashriTMM requested changes

2023-12-14 05:34 UTC, meenashriTMM commented on Training/Program.cs
> +         s ??= s.Trim ().ToLower ();
This is incorrect. You are saying if s is null, do s.Trim () !!!!
Just do the null check before this line is executed.

2024-01-02 12:55 UTC, meenashriTMM approved these changes

2024-01-02 12:55 UTC, closed without merging