A9: Expression evaluator
Ashish02112001/Training pull request #39
Opened 2023-12-14 10:41 UTC by Ashish02112001

2023-12-15 06:34 UTC, varalakshmi-imm requested changes
-sin45 and sin90*2 are not working properly as expected.
Sent you the test data in teams, please check.

2023-12-16 06:55 UTC, varalakshmi-imm reviewed
@Ashish02112001 Functionality test done, as the test data works. 
Since the changesets are not related only to unary operator this review will take some time.

2023-12-27 08:21 UTC, varalakshmi-imm reviewed
Please redo in a separate branch with the original code from the academy notes in main and just do the changes for unary operator in the branch.
Work on this after you complete all your academy assignments.

2024-01-03 04:55 UTC, varalakshmi-imm requested changes

2024-01-03 04:55 UTC, varalakshmi-imm commented on Eval/Tokenizer.cs
> +               mEval.BasePriority += ch == '(' ? 10 : -10;
Why is this moved here?

2024-01-03 04:55 UTC, varalakshmi-imm commented on Eval/Evaluator.cs
> +            mOperands.Push (unary.Apply (f1)); break;
```suggestion
            mOperands.Push (unary.Evaluate (f1)); break;

```
Like other TOps this should also have Evaluate method instead of Apply.

2024-01-03 04:55 UTC, varalakshmi-imm commented on Eval/Evaluator.cs
> +            if (op is TOpUnary) {mOperators.Push (op); break;}
Why do we have push and break for Unary here?
Anyways after while loop, the op is pushed into mOperators.

2024-01-03 04:55 UTC, varalakshmi-imm commented on Eval/Tokenizer.cs
> +               if (ch is '-' or '+' && (mN - 1 == 0 || mText[mN - 2] is '+' or '-' or '*' or '/' or '^' or '(' || mFuncs.Contains (mText[0..(mN - 1)]))) return new TOpUnary (mEval, ch);
```suggestion
               if (ch is '-' or '+' && (mN - 1 == 0 || mText[mN - 2] is '+' or '-' or '*' or '/' or '^' or '(' || mFuncs.Contains (mText[0..(mN - 1)]))) return new TOpUnary (mEval, ch);

```
Why is this check for all arithmetic operators done here? Should check only for - or + right?

2024-01-03 07:42 UTC, Ashish02112001 commented on Eval/Tokenizer.cs
> +               mEval.BasePriority += ch == '(' ? 10 : -10;
If this is in evaluator it is not working properly mam

2024-01-04 04:10 UTC, varalakshmi-imm commented on Eval/Tokenizer.cs
> +               mEval.BasePriority += ch == '(' ? 10 : -10;
okay

2024-01-04 04:31 UTC, varalakshmi-imm requested changes

2024-01-04 04:31 UTC, varalakshmi-imm commented on Eval/Evaluator.cs
> +         var token = tokenizer.Next (tokens);
Passing all tokens is not good

2024-01-04 04:31 UTC, varalakshmi-imm commented on Eval/Tokenizer.cs
> +               if (ch is '+' or '-' && tokens.Count == 0 || tokens[^1] is TOperator or TPunctuation { Punct: '(' } or TOpUnary) return new TOpUnary (mEval, ch);
Just see if you can do this without tokens parameter by storing a previous token.

2024-01-04 04:31 UTC, varalakshmi-imm commented on Eval/Token.cs
> +   public double Evaluate (double n) {
This could be defined as an expression body method.
```suggestion
   public double Evaluate (double n) => Unary == '+' ? n : -n;

```

2024-01-05 04:27 UTC, varalakshmi-imm requested changes

2024-01-05 04:27 UTC, varalakshmi-imm commented on Eval/Tokenizer.cs
> +   public Token mPrev;
Need not be public. Assign mPrev in this Next method itself instead of setting in Evaluator.

2024-01-05 05:11 UTC, Ashish02112001 commented on Eval/Tokenizer.cs
> +   public Token mPrev;
How can I access it from here mam? Evaluator only contains the token list.

2024-01-05 05:37 UTC, varalakshmi-imm commented on Eval/Tokenizer.cs
> +   public Token mPrev;
You are setting mPrev of Tokenizer using Next method of Tokenizer. So it should obviously be set in Next method as shown below:
![image](https://github.com/Ashish02112001/Training/assets/75829713/a9a82c24-bce4-4763-961a-fe9785d16d41)

2024-01-05 05:38 UTC, varalakshmi-imm requested changes
Make mPrev private and set it in Next method of Tokenizer itself.

2024-01-05 07:20 UTC, varalakshmi-imm approved these changes

2024-01-05 07:20 UTC, closed without merging