A10.2: Double ended queue
Ashish02112001/Training pull request #41
Opened 2023-12-22 11:18 UTC by Ashish02112001

2023-12-23 07:55 UTC, varalakshmi-imm requested changes

2023-12-23 07:55 UTC, varalakshmi-imm commented on Training/Program.cs
> +   public class DEndTQueue<T> {
```suggestion
   public class TDQueue<T> {

```
Naming not good. We had TStack, TQueue etc so should have named like that.

2023-12-23 07:55 UTC, varalakshmi-imm commented on Training/Program.cs
> +      void ResizeArr () {
```suggestion
      void Resize () {

```
Naming not good. Either Resize or ResizeArray. Should be meaningful names.

2023-12-23 07:55 UTC, varalakshmi-imm commented on Training/Program.cs
> +         if (rear < front) expArray = (mElements[front..mElements.Length].Concat (mElements[0..(rear + 1)])).ToArray ();
Can you explain why you need this?

2023-12-23 07:55 UTC, varalakshmi-imm commented on Training/Program.cs
> +      int front = -1, rear = -1, mCount = 0;
Why not zero for front and rear?

2023-12-23 07:55 UTC, varalakshmi-imm commented on Training/Program.cs
> +         T frontElem = mElements[front];
```suggestion
         T a = mElements[front];

```

2023-12-23 07:55 UTC, varalakshmi-imm commented on Training/Program.cs
> +         T rearElem = mElements[rear--];
```suggestion
         T a = mElements[rear--];

```

2023-12-26 03:23 UTC, Ashish02112001 commented on Training/Program.cs
> +         if (rear < front) expArray = (mElements[front..mElements.Length].Concat (mElements[0..(rear + 1)])).ToArray ();
If the rear is next to front while the array is full, elements added by front enqueue is added front (from 0th index) and elements enqueued by rear will be added at rear side and then array size is doubled.

2023-12-26 03:25 UTC, Ashish02112001 commented on Training/Program.cs
> +      int front = -1, rear = -1, mCount = 0;
I have written in such a way that if the elements are to be enqueued into the array then the index starts from 0.

2023-12-26 03:57 UTC, varalakshmi-imm requested changes

2023-12-26 03:57 UTC, varalakshmi-imm commented on Training/Program.cs
> +      int front = -1, rear = -1, mCount = 0;
I am saying set both as zero and simplify the code. Use % to set the rear and front instead of checking for -1.

2023-12-26 03:57 UTC, varalakshmi-imm commented on Training/Program.cs
> +         if (rear < front) expArray = (mElements[front..mElements.Length].Concat (mElements[0..(rear + 1)])).ToArray ();
This is unnecessary. As it is a circular array, resizing and then setting the front or rear properly will work properly. So fix this.

2023-12-27 03:47 UTC, varalakshmi-imm requested changes

2023-12-27 03:47 UTC, varalakshmi-imm commented on Program.cs
> -// ------------------------------------------------------------------------
This should also be until 96 column like the first line.

2023-12-27 03:47 UTC, varalakshmi-imm commented on Test/UnitTest1.cs
> +         Assert.AreEqual (1, mNums.RearDequeue ());
Do this in a loop

2023-12-27 03:47 UTC, varalakshmi-imm commented on Test/UnitTest1.cs
> +         Assert.AreEqual (5, mNums.FrontDequeue ());
Do this in a loop

2023-12-27 03:47 UTC, varalakshmi-imm commented on Test/UnitTest1.cs
> +         mNums.RearEnqueue (1);
Refactor all the tests by using loops

2023-12-27 03:47 UTC, varalakshmi-imm commented on Training/Program.cs
> +      static void Main (string[] args) {
![image](https://github.com/Ashish02112001/Training/assets/75829713/17e71212-d36e-4c7a-abc6-da07a8f6a95a)

2023-12-27 03:47 UTC, varalakshmi-imm commented on Training/Program.cs
> +      int front = 0, rear = 0, mCount = 0, mSize = 4;
```suggestion
      int mFront = 0, mRear = 0, mCount = 0, mSize = 4;

```
Member variables should start with m

2023-12-27 03:47 UTC, varalakshmi-imm commented on Training/Program.cs
> +      int front = 0, rear = 0, mCount = 0, mSize = 4;
No need for both mSize and mCount. Use mCount alone then the code will look clean.
In the constructor you can hard code as 4 instead of mSize.

2023-12-27 03:47 UTC, varalakshmi-imm commented on Training/Program.cs
> +         T[] expArray = new T[mCount * 2];
Simplify as shown below:
```
T[] tmp = new T[mCount * 2];
for (int i = 0; i < mCount; i++)
   tmp[i] = mElements[(front + i) % mCount];
(mElements, front, rear) = (tmp, 0, mCount);
```

2023-12-27 08:04 UTC, varalakshmi-imm approved these changes

2023-12-27 08:05 UTC, closed without merging