A14.1: Anagrams
Ashish02112001/Training pull request #46
Opened 2024-01-31 06:41 UTC by Ashish02112001

2024-02-08 07:26 UTC, v-priya requested changes

2024-02-08 07:26 UTC, v-priya commented on Program.cs
> +         Func<string, string> sortedWord = word => new string (word.ToCharArray ().OrderBy (x => x).ToArray ());
Any specific reason for having this as a separate delegate? Also, not necessary to convert to a char array. Order can be directly done on string (as it a collection of chars). Can use `Order ()` instead of `OrderBy (a => a)` as there is no particular property by which we specify the ordering.

2024-02-08 07:26 UTC, v-priya commented on Program.cs
> +            if (anagrams.TryGetValue (sWord, out List<string>? anagramWord)) anagramWord.Add (word);
Can use `var` instead of `List<string>?`. Use shorter variable names. For example, `list` instead of `anagramWord`

2024-02-08 07:26 UTC, v-priya commented on Program.cs
> +         Console.WriteLine (@"Anagrams are stored in \bin\Debug\net7.0\Anagrams.txt");
Directly output to console, instead of writing to file.

2024-02-08 08:47 UTC, Ashish02112001 commented on Program.cs
> +         Func<string, string> sortedWord = word => new string (word.ToCharArray ().OrderBy (x => x).ToArray ());
No specific reason akka. Just tried using it.

2024-07-30 10:12 UTC, v-priya approved these changes

2024-07-30 10:12 UTC, closed without merging